### ISSUE TITLE
confusion con esta regla

### ISSUE THREAD

**Issue by DenJohX** [arduinoguate/ArduChallenge#12]
"Si un participante empuja a un contrincante hacia una estructura y este pierde un globo se le suma un punto al contrincante"

En esta oración identifique al sujeto, deduzca quién es el contrincante e indique quién gana puntos xD. 

Ya en serio, no entiendo si gana puntos el que empuja o el empujado.

**Comment by yeffrimic** [comment]
Se le suma el punto al participante que empujó al otro hacia la estructura
Vaya el atacante
